### PR TITLE
Baremetrics Mimic

### PR DESCRIPTION
**Pull request by UrbanFish**
My attempt to mimic Baremetrics date range picker

### CODE REVIEW

**Comment by smeriwether** [comment]
Do you mind fixing the merge conflicts?

**Comment by smeriwether** [comment]
Do you mind fixing the merge conflicts?

**Comment by osxi** [comment]
Do you mind fixing the merge conflicts?

**Comment by osxi** [comment]
Do you mind fixing the merge conflicts?

**Comment by iterion** [comment]
Closing, reopen if we ever come back to this.

**Pull request closed without merging**
