### PR TITLE
Starting single date picker

### PR DESCRIPTION
**Pull request by iterion**
Adding single date picker. Tests are just stubs and CSS needs a little bit of work.

### CODE REVIEW

**Comment by smeriwether** [comment]
Do you mind fixing the merge conflicts?

**Comment by smeriwether** [comment]
Do you mind fixing the merge conflicts?

**Comment by osxi** [comment]
Do you mind fixing the merge conflicts?

**Comment by osxi** [comment]
Do you mind fixing the merge conflicts?

**Pull request closed without merging**
